/* Generated by bin2c, do not edit manually */
#ifndef WAVE_H
    #define WAVE_H

    #include <stdint.h>

    /* Number of elements in the wave sound track */
    #define WAVE_SIZE 63214u//27494u //79910u//

    /* Extern reference to the wave sound track data */
    extern const int16_t wave_data[WAVE_SIZE];

#endif
